In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

print(arr[0])

1


In [5]:
# Boolean indexing
print(arr[arr > 2])
print(arr[arr % 2  == 0])
print(arr[arr % 2  != 0])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [6]:
# slicing

print(arr[0:4]) # [starting, ending, step]

[1 2 3 4]
