In [7]:
# !pip install numpy
import numpy as np
import time

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [13]:
size = 1_00_000

start_time = time.time()
py_list = list(range(size))
sq_list = [x**2 for x in py_list]
end_time = time.time()
print(end_time - start_time)

start_time = time.time()

np_array = np.array(py_list)
sq_array = np_array ** 2
end_time = time.time()
print(end_time - start_time)


0.010910987854003906
0.004636287689208984


In [17]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1, arr1.shape)

[1 2 3 4 5 6] (6,)


In [16]:
arr2D = np.array([ [1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
print(arr2D , arr2D.dtype)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]] int64


In [19]:
arr3 = np.zeros((2,3), dtype="int64")
print(arr3, arr3.dtype)

[[0 0 0]
 [0 0 0]] int64


In [20]:
arr4 = np.ones((5,), dtype="int64")
print(arr4, arr4.dtype)

[1 1 1 1 1] int64


In [21]:
arr5 = np.full((2,3), 100)
print(arr5, arr5.dtype)

[[100 100 100]
 [100 100 100]] int64


In [22]:
arr6 = np.eye(3)
print(arr6, arr.dtype,arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] int64 (5,)


In [24]:
arr7 = np.arange(1,10)
print(arr7)

[1 2 3 4 5 6 7 8 9]
