In [1]:
import numpy as np

In [4]:
arr = np.array([[2,3,4],[5,6,7]])

print(arr, arr.shape)

reshaped = arr.reshape(3,2)

print(reshaped, reshaped.shape)

flat = reshaped.flatten();

print(flat , flat.shape)

[[2 3 4]
 [5 6 7]] (2, 3)
[[2 3]
 [4 5]
 [6 7]] (3, 2)
[2 3 4 5 6 7] (6,)
